FROM node:lts-alpine AS builder
RUN apk add --no-cache openssl
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY tsconfig.json .
COPY prisma ./prisma
COPY src ./src
RUN npx prisma generate && npm run build

FROM node:lts-alpine AS runner
RUN apk add --no-cache openssl
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/prisma ./node_modules/prisma
COPY --from=builder /app/dist ./dist
COPY prisma ./prisma
EXPOSE 3000
CMD ["sh", "-c", "node node_modules/.bin/prisma db push --skip-generate && node dist/index.js"]
